highlights:
  -
    tegename: '目撃者たちの夜'
    tegedescription: 'まったく新しいロール決めの、正体隠匿ゲーム！'
    tegeinspiration: '目撃された殺人鬼はどう動くのか。人狼並みの議論が楽しめます'
  -
    tegename: 'ふくろと金貨'
    tegedescription: 'バレないように金貨を奪え！'
    tegeinspiration: '相手を出し抜いたり、宝石で騙したりする戦略ゲーム'
  -
    tegename: 'Marrakech'
    tegedescription: 'Marrakechとはモロッコの都市の名前で、ついにボードゲームになりました。'
    tegeinspiration: '敵の絨毯を邪魔しつつ、自分の絨毯を広げよう！'
