rules:
  -
    tegeicon: 'flaticon-gym'
    tegephrase: '笑顔'
    tegeactivity: 'ゲームは楽しくなくては！自然と笑みがこぼれます'
  -
    tegeicon: 'flaticon-woman'
    tegephrase: '交流'
    tegeactivity: '初心者から経験者まで大歓迎！リアルなイベントが中心です'
  -
    tegeicon: 'flaticon-workout'
    tegephrase: '多様'
    tegeactivity: '仲間とボードゲームでつながる集まりです'
  -
    tegeicon: 'flaticon-meditation'
    tegephrase: '共有'
    tegeactivity: '今どきのテーブルゲームのトピックが手に入ります'
  -
    tegeicon: 'flaticon-stationary-bike'
    tegephrase: '口コミ'
    tegeactivity: '一緒にテーブルゲームしてくれる人、興味がある人、募集！'
